### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by koriym** [WyriHaximus/php-list-classes-in-directory#38]
```
% ./vendor/bin/phpunit 
PHP Warning:  "resource" is not a supported builtin type and will be interpreted as a class name. Write "\Safe\resource" or import the class with "use" to suppress this warning in /Users/akihito/git/php-list-classes-in-directory/vendor/thecodingmachine/safe/generated/sockets.php on line 797

Warning: "resource" is not a supported builtin type and will be interpreted as a class name. Write "\Safe\resource" or import the class with "use" to suppress this warning in /Users/akihito/git/php-list-classes-in-directory/vendor/thecodingmachine/safe/generated/sockets.php on line 797
PHP Warning:  "integer" will be interpreted as a class name. Did you mean "int"? Write "\Safe\integer" or import the class with "use" to suppress this warning in /Users/akihito/git/php-list-classes-in-directory/vendor/thecodingmachine/safe/generated/swoole.php on line 17

Warning: "integer" will be interpreted as a class name. Did you mean "int"? Write "\Safe\integer" or import the class with "use" to suppress this warning in /Users/akihito/git/php-list-classes-in-directory/vendor/thecodingmachine/safe/generated/swoole.php on line 17
PHPUnit 8.5.21 by Sebastian Bergmann and contributors.
```

If I run composer install with `ignore-platform-reqs`, I get the above warning, but the tests all pass in PHP8

```
......                                                              6 / 6 (100%)
```

**Comment by WyriHaximus** [comment]
Just tagged [`1.4`](https://github.com/WyriHaximus/php-list-classes-in-directory/releases/tag/1.4.0) to add PHP 8+ support. Also snook in some QA upgrades

**Comment by koriym** [comment]
@WyriHaximus Arigato!

**Comment by koriym** [comment]
I'm probably missing something, but please help me out.

Your package require `roave/better-reflection": "^4 || ^3.1 || ^2"`
https://github.com/WyriHaximus/php-list-classes-in-directory/blob/master/composer.json#L13

But roave/better-reflection ^4 does not support PHP8 (5.0.x supports)
https://packagist.org/packages/roave/better-reflection#4.12.2

But your tests does not fail. composer install in your repo does not fail. (why???)
But when I try to use your package in my package, it failed as followed.

```
  Problem 1
    - roave/better-reflection 2.0.0 requires php >7.1.0,<7.3.0 -> your php version (8.0.12) does not satisfy that requirement.
    - roave/better-reflection[2.0.1, ..., 2.0.2, 3.1.0, ..., 3.1.1] require php >=7.1.0,<7.3.0 -> your php version (8.0.12) does not satisfy that requirement.
    - roave/better-reflection[3.2.0, ..., 3.3.0] require php >=7.1.0,<7.4.0 -> your php version (8.0.12) does not satisfy that requirement.
    - roave/better-reflection 3.4.0 requires php >=7.2.0,<7.4.0 -> your php version (8.0.12) does not satisfy that requirement.
    - roave/better-reflection[3.5.0, 4.0.0, ..., 4.3.0] require php >=7.2.0,<7.5.0 -> your php version (8.0.12) does not satisfy that requirement.
    - roave/better-reflection[4.4.0, ..., 4.12.2] require php >=7.4.1,<7.5.0 -> your php version (8.0.12) does not satisfy that requirement.
    - wyrihaximus/list-classes-in-directory 1.4.0 requires roave/better-reflection ^4 || ^3.1 || ^2 -> satisfiable by roave/better-reflection[2.0.0, 2.0.1, 2.0.2, 3.1.0, ..., 3.5.0, 4.0.0, ..., 4.12.2].
    - Root composer.json requires wyrihaximus/list-classes-in-directory ^1.4 -> satisfiable by wyrihaximus/list-classes-in-directory[1.4.0].
    - 
```

**Comment by WyriHaximus** [comment]
You're not missing anything, I'm waiting for https://github.com/Roave/BetterReflection/issues/904 

Could look into if that dependency is still required at this point, but not sure if possible.

P.S. Sorry bout this, I completely forgot about this dependency and since I kept support for `7.4` composer won't complain if you require it. Been working on that in https://github.com/WyriHaximus/php-test-utilities/pull/332, but that runs into exactly this issue :zipper_mouth_face:

**Comment by koriym** [comment]
@WyriHaximus Ok, Let's wait.

**Comment by WyriHaximus** [comment]
@koriym Looks like it won't be long now: https://github.com/Roave/BetterReflection/issues/904#issuecomment-999741158

**Comment by WyriHaximus** [comment]
FIled #41 as a first step, waiting for https://github.com/Roave/BackwardCompatibilityCheck/pull/368 next. Once that is merged and released I'll release a new version of this package as well.

**Comment by WyriHaximus** [comment]
@koriym Ok it should work now, [`1.5.0`](https://github.com/WyriHaximus/php-list-classes-in-directory/releases/tag/1.5.0) is out with BR 5
