### ISSUE TITLE
changing the package name ?

### ISSUE THREAD

**Issue by azjezz** [WyriHaximus/php-list-classes-in-directory#6]
the package is under 'wyrihaximus/list-classes-in-directory', so is the repository name.
but now its seems to do more.

- list classes in directory
- list classes in multiple directories 
- list classes in file 
- list classes in multiple files 

maybe something like 'wyrihaximus/class-fetch' ? or simply 'wyrihaximus/list-classes' 

but that's totally up to you.

**Comment by WyriHaximus** [comment]
Yeah not sure, could do that but it wouldn't be the first package that does more then what it initially was created for :smile:

**Comment by azjezz** [comment]
well, at least the description should be updated.

![image](https://user-images.githubusercontent.com/29315886/47260662-be344380-d4b7-11e8-844c-7072b889a847.png)

--- 

![image](https://user-images.githubusercontent.com/29315886/47260669-cee4b980-d4b7-11e8-8485-0a5beb15fa95.png)

**Comment by WyriHaximus** [comment]
Ow that can be done in `composer.json`.`description`, feel up for another PR? :stuck_out_tongue_closed_eyes:

**Comment by azjezz** [comment]
sure :stuck_out_tongue:

**Comment by azjezz** [comment]
nothing more to do here i guess ~
